/**
 * Runnable, no-API-key twin of react-repo-assistant.ts. A scripted stub model
 * drives the two-phase lifecycle so you can watch the returned tree change:
 *
 *   bun run examples/react-demo.ts
 *
 * Turn 1 (explore): the "model" calls EnterEditMode → setState flips the phase.
 * Turn 2 (edit):     the tree now returns WriteFile, which runs and writes a file.
 */

import { mkdtempSync } from "node:fs"
import { readFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { Effect, Layer, Stream } from "effect"
import type { JsonToolCall } from "@hypen-space/gloop-loop"
import { AIProvider, type AIProviderImpl } from "../src/index.js"
import {
  buildAgent,
  group,
  model,
  system,
  tool,
  useState,
  useTurn,
} from "../src/react/index.js"

const dir = mkdtempSync(join(tmpdir(), "gloop-react-"))
const target = join(dir, "NOTES.md")

// --- The component: identical shape to the real example -------------------

function Assistant() {
  const [phase, setPhase] = useState<"explore" | "edit">("explore")
  const turn = useTurn()
  process.stderr.write(`\n[turn ${turn.turn}] rendering phase=${phase}\n`)

  return group(
    model("stub"),
    system(`You are gloop. phase=${phase}`),
    tool("ReadFile").arg("path", "path").handle((a) => readFile(a.path!, "utf8")),

    phase === "explore"
      ? tool("EnterEditMode")
          .describe("Unlock writing")
          .handle(() => {
            setPhase("edit") // schedules a rerender — next turn's tree differs
            return "edit mode unlocked"
          })
      : tool("WriteFile")
          .arg("path", "path")
          .arg("contents", "contents")
          .handle((a) => Bun.write(a.path!, a.contents ?? "").then(() => `wrote ${a.path}`)),
  )
}

// --- A tiny scripted stub provider ----------------------------------------

const call = (name: string, args: object): JsonToolCall => ({
  id: `c_${name}`,
  type: "function",
  function: { name, arguments: JSON.stringify(args) },
})

const script: ReadonlyArray<{ text: string; toolCalls?: JsonToolCall[] }> = [
  { text: "", toolCalls: [call("EnterEditMode", {})] }, // turn 1: flip phase
  { text: "Explored. Switching to edit mode." }, // turn 1 continues
  { text: "", toolCalls: [call("WriteFile", { path: target, contents: "# Notes\nGenerated by gloop.\n" })] }, // turn 2: write
  { text: "Done — wrote NOTES.md." }, // turn 2 continues
]

let i = 0
const stub: AIProviderImpl = {
  name: "stub",
  complete: (req) => {
    const r = script[Math.min(i++, script.length - 1)]!
    return Effect.succeed({
      id: `s${i}`,
      model: req.model,
      content: r.text,
      finishReason: r.toolCalls?.length ? "tool_calls" : "stop",
      toolCalls: r.toolCalls,
    })
  },
  stream: (req) => {
    const r = script[Math.min(i++, script.length - 1)]!
    return {
      chunks: Stream.fromIterable(r.text ? [r.text] : []),
      result: Effect.succeed({
        id: `s${i}`,
        model: req.model,
        content: r.text,
        finishReason: r.toolCalls?.length ? "tool_calls" : "stop",
        toolCalls: r.toolCalls,
      }),
      cancel: Effect.void,
    }
  },
}

// --- Run it ---------------------------------------------------------------

const program = Effect.gen(function* () {
  const app = yield* buildAgent(Assistant)

  const names = () => app.agent.registry.names
  process.stderr.write(`explore-phase tools: ${JSON.stringify(yield* names())}\n`)

  yield* app.agent.eventsOf("StreamChunk").pipe(
    Stream.runForEach((e) => Effect.sync(() => process.stdout.write(e.text))),
    Effect.forkScoped,
  )

  process.stderr.write("\n--- send #1 (explore) ---")
  yield* app.send("look around, then switch to edit mode")
  process.stderr.write(`\nafter turn 1, tools: ${JSON.stringify(yield* names())}\n`)

  process.stderr.write("\n--- send #2 (edit) ---")
  yield* app.send("write NOTES.md")
  process.stderr.write(`\nafter turn 2, tools: ${JSON.stringify(yield* names())}\n`)

  const written = yield* Effect.promise(() => readFile(target, "utf8"))
  process.stderr.write(`\n=== ${target} ===\n${written}`)
})

Effect.runPromise(Effect.scoped(program).pipe(Effect.provide(Layer.succeed(AIProvider, stub)))).catch(
  (e) => {
    console.error(e)
    process.exit(1)
  },
)
